version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_0900_ai_ci"
    ]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gridgestagram
      MYSQL_USER: kim
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    ports:
      - "3309:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: