jwt:
  secret: ${jwt.secret}
  token:
    expiration: 86400  # 24시간 (초)
  refresh-token:
    expiration: 604800  # 7일 (초)


spring:
  config:
    import: 'aws-parameterstore:/config/gridgestagram_prod/'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/gridgestagram?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_ko_0900_ai_ci&serverTimezone=Asia/Seoul
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${spring.security.oauth2.client.registration.kakao.client-id}
            client-secret: ${spring.security.oauth2.client.registration.kakao.client-secret} # 선택, 있으면 등록
            redirect-uri: "http://3.39.0.54:8080/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false

  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}


cloud:
  aws:
    region:
      static: ${cloud.aws.region.static}
    credentials:
      access-key: ${cloud.aws.credentials.access-key}
      secret-key: ${cloud.aws.credentials.secret-key}
    s3:
      bucket: ${cloud.aws.s3.bucket}
aws:
  paramstore:
    enabled: true
    prefix: /config
    profile-separator: _
    name: gridgestagram